
dac_path: ./models/codec.pth
save_path: runs/base-disco-400m

num_iters: 1000002
save_iters: [100000, 200000, 400000, 600000, 1000000]
val_idx: [0, 1, 2, 3, 4]
sample_freq: 10000
val_freq: 2500

batch_size: 32
val_batch_size: 32
num_workers: 16
grad_acc_batches: 1

# Optimizatio
amp: false
compile: false

AdamW.lr: 0.001
# AdamW.eps: 0.0001

NoamScheduler.factor: 2.0
NoamScheduler.warmup: 3000

VampNet.vocab_size: 1024
VampNet.n_codebooks: 9
VampNet.n_conditioning_codebooks: 0
VampNet.embedding_dim: 1280
VampNet.n_layers: 20
VampNet.n_heads: 20
VampNet.dropout: 0.05
VampNet.max_seq_len: 1024
VampNet.flash_attn: true

DACDataset.metadata_csvs: 
# - ./data/metadata/spotdl.csv
# - ./data/metadata/prosound_redacted.csv
# - ./data/metadata/fma_full.csv
- ./data/metadata/disco-1m.csv

DACDataset.seq_len: 1024
train/DACDataset.split: "train"
val/DACDataset.split: "val"
val/DACDataset.length: 2000
test/DACDataset.split: "test"
test/DACDataset.length: 4000

compute_loss_on_masked_tokens_only: True
