$include:
  - conf/base.yml

fine_tune: True
fine_tune_checkpoint: ./models/vampnet.pth

train/DACDataset.length: 100000000
val/DACDataset.length: 500

NoamScheduler.warmup: 10000

batch_size: 12
val_batch_size: 12
num_workers: 12
save_iters: [10000, 20000,  50000, 100000, 500000]
sample_freq: 5000
val_freq: 2500

AdamW.lr: 0.0001

num_iters: 500000

train/DACDataset.split: null
val/DACDataset.split: null
test/DACDataset.split: null