$include:
    - conf/vampnet.yml

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~ model // training config ~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
VampNetTrainer.prefix_tag: "bbcsub"
VampNetTrainer.text_cond: "clap"
VampNetTrainer.mode: "stemgen"

VampNetTrainer.embedding_dim: 792
VampNetTrainer.n_layers: 12
VampNetTrainer.n_heads: 12

batch_size: 16
accumulate_grad_batches: 2


# the datbase config 
# ~~~~~~~~~~~~~~~~~~
db_path: ./sm.db
query: "
    SELECT af.path, chunk.offset, chunk.duration, af.duration as total_duration, dataset.name 
    FROM chunk 
    JOIN audio_file as af ON chunk.audio_file_id = af.id 
    JOIN dataset ON af.dataset_id = dataset.id
    WHERE dataset.name IN ('bbc-subset')
"
