
codec_ckpt: /home/hugo/.cache/descript/dac/weights_44khz_8kbps_0.0.1.pth 
save_path: ckpt

num_iters: 1000000000
save_iters: [10000, 50000, 100000, 300000, 500000]
val_idx: [0,1,2,3,4,5,6,7,8,9]
sample_freq: 10000
val_freq: 1000


# Optimization
amp: false

CrossEntropyLoss.label_smoothing: 0.1

AdamW.lr: 0.001

VampNet.vocab_size: 1024
VampNet.n_codebooks: 4
VampNet.n_conditioning_codebooks: 0
VampNet.r_cond_dim: 0
VampNet.noise_mode: mask
VampNet.embedding_dim: 1000
VampNet.n_layers: 20
VampNet.n_heads: 20
VampNet.flash_attn: false
VampNet.dropout: 0.0

# Data
batch_size: 16
num_workers: 10
Dataset.n_samples: 220160 # roughly 5 seconds, matching a 512 sample hop len at 44.1k

build_datasets.db_path: /home/hugo/soup/scratch/data-fast/sm.db
build_datasets.query: "SELECT * from audio_file JOIN dataset WHERE dataset.name = 'vctk' "
