
codec_ckpt: /home/hugo/.cache/descript/dac/weights_44khz_8kbps_0.0.1.pth 
save_path: ckpt

num_iters: 1000000000
save_iters: [10000, 50000, 100000, 300000, 500000]
val_idx: [0,1,2,3,4,5,6,7,8,9]
sample_freq: 10000
val_freq: 1000


# Optimization
CrossEntropyLoss.label_smoothing: 0.0

AdamW.lr: 0.001

VampNet.vocab_size: 1024
VampNet.n_codebooks: 9
VampNet.n_conditioning_codebooks: 0
VampNet.r_cond_dim: 0
VampNet.noise_mode: mask
VampNet.embedding_dim: 774
VampNet.n_layers: 8
VampNet.n_heads: 8
VampNet.flash_attn: true
VampNet.dropout: 0.0

# Data
batch_size: 32
num_workers: 10
# Dataset.n_samples: 79872 # roughly 1.814 seconds, matching a 512 sample hop len at 44.1k
Dataset.n_samples: 220160 # roughly 4.99 seconds, matching a 512 sample hop len at 44.1k
Dataset.use_chunk_table: true

# build_datasets.db_path: /media/pancho/sm.db
build_datasets.db_path: /home/hugo/soup/scratch/data-fast/sm.db
build_datasets.query: "
    SELECT af.path, chunk.offset, chunk.duration, af.duration as total_duration, dataset.name 
    FROM chunk 
    JOIN audio_file as af ON chunk.audio_file_id = af.id 
    JOIN dataset ON af.dataset_id = dataset.id
    WHERE dataset.name IN ('choral-singing-dataset')
"

    # WHERE dataset.name IN ('mtg-jamendo', 'dagstuhl-choir-set', 'choral-singing-dataset')
