$include:
  - conf/vampnet.yml

fine_tune: True

train/AudioDataset.n_examples: 100000000
val/AudioDataset.n_examples: 500


NoamScheduler.warmup: 500

batch_size: 7
num_workers: 7
save_iters: [2000, 4000, 10000, 20000, 40000, 100000]
sample_freq: 2000
val_freq: 1000

AdamW.lr: 0.0001

# let's us organize sound classes into folders and choose from those sound classes uniformly
AudioDataset.without_replacement: False
num_iters: 500000
