encoder_ckpt: "/home/hugo/.cache/descript/dac/weights_44khz_8kbps_0.0.1.pth"

# Optimization
AdamW.betas: [0.8, 0.99]
AdamW.lr: 0.0001
ExponentialLR.gamma: 0.999996

amp: false
val_batch_size: 100
device: cuda
num_iters: 400000
save_iters: [10000, 50000, 100000, 200000]
valid_freq: 1000
sample_freq: 2000
num_workers: 20
val_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
seed: 0
lambdas:
  mel/loss: 1.0
  # stft/loss: 1.0
  # crepe/loss: 500.0
  # clap/loss: 1

VolumeNorm.db: [const, -16]
# VolumeChange.db: [uniform, -6, 6]

# Transforms
build_transform.preprocess:
  - Identity
build_transform.augment_prob: 0.0
build_transform.augment:
  - Identity
build_transform.postprocess:
  - VolumeNorm
  - RescaleAudio
  - ShiftPhase

# Loss setup
MultiScaleSTFTLoss.window_lengths: [2048, 512]
MelSpectrogramLoss.n_mels: [5, 10, 20, 40, 80, 160, 320]
MelSpectrogramLoss.window_lengths: [32, 64, 128, 256, 512, 1024, 2048]
MelSpectrogramLoss.mel_fmin: [0, 0, 0, 0, 0, 0, 0]
MelSpectrogramLoss.mel_fmax: [null, null, null, null, null, null, null]
# MelSpectrogramLoss.n_mels: [20, 40, 80, 160]
# MelSpectrogramLoss.window_lengths: [512, 512, 1024, 2048]
# MelSpectrogramLoss.mel_fmin: [0, 0, 0, 0]
# MelSpectrogramLoss.mel_fmax: [null, null, null, null]
MelSpectrogramLoss.pow: 1.0
MelSpectrogramLoss.clamp_eps: 1.0e-5
MelSpectrogramLoss.mag_weight: 0.0

# Data
batch_size: 72
# train/Dataset.n_samples: 32768 # 0.68s
train/Dataset.n_samples: 132300 # 0.68s
# train/Dataset.n_samples: 239616 # 0.68s
val/Dataset.n_samples: 239616 # roughly 5 seconds
val/Dataset.max_examples: 2000 # roughly 0.68 seconds

# build_datasets.db_path: /home/hugo/soundmaterial/clack.db
build_datasets.db_path: /home/hugo/descript-audio-codec/vctk.db
build_datasets.query: "SELECT * from audio_file"
